---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-namespace-labeller
rules:
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - 'list'
  - 'get'
  - 'patch'
